### PR TITLE
Include CORESPONSE (RWTH Aachen project)

### PR DESCRIPTION
**Pull request by pepae**

### CODE REVIEW

**Comment by bneiluj** [comment]
do you have an image ?

**Comment by pepae** [comment]
https://coresponse.github.io/blog/images/concept_crank2_v0/Rendering_Hebel_II_V1_cc.png this maybe, but it's a rendering

**Comment by Tuebel** [comment]
Hey, I'm working on the CORESPONSE project. If you would like, we could provide you with real images of our latest prototypes. Thanks for creating this list!

**Comment by bneiluj** [comment]
That would be awesome. Please make a pull request or post the images here.

**Comment by bneiluj** [comment]
You can create a new folder into the assets folder and add a link to the README that points to the folder.

**Comment by Tuebel** [comment]
Okay I created a new pull request #5

**Pull request merged**
